package com.flipfit.bean;

// TODO: Auto-generated Javadoc
/**
 * The Class User.
 *
 * This class represents a generic user in the FlipFit system.
 * It acts as a base class for specific user roles such as
 * Admin, GymOwner, and GymCustomer.
 *
 * It contains common user attributes like name, email,
 * password, role ID, and active status.
 *
 * @author Shravya
 * @ClassName "User"
 */
public class User {

    /** The unique user ID (auto-generated by database) */
    private int userId;

    /** The user's full name */
    private String name;

    /** The user's email address */
    private String email;

    /** The user's phone number */
    private String phone;

    /** The user's login password */
    private String password;

    /** The role ID of the user (1 = Customer, 2 = Owner, 3 = Admin) */
    private int roleId;

    /** Indicates whether the user account is active */
    private boolean isActive;

    private String identityNo;

    public String getIdentityNo() {
        return identityNo;
    }

    public void setIdentityNo(String identityNo) {
        this.identityNo = identityNo;
    }

    private boolean isApproved;

    /**
     * Instantiates a new User.
     *
     * This constructor is typically used during registration.
     *
     * @param userId the user ID
     * @param name the user's full name
     * @param email the user's email address
     * @param phone the user's phone number
     * @param password the user's password
     * @param roleId the role ID
     */
    public User(int userId, String name, String email,
                String phone, String password, int roleId) {

        this.userId = userId;
        this.name = name;
        this.email = email;
        this.phone = phone;
        this.password = password;
        this.roleId = roleId;
        this.isActive = true;
    }

    /**
     * Instantiates a new User.
     *
     * Default constructor used for ResultSet mapping.
     */
    public User() {}

    /**
     * Gets the user ID.
     *
     * @return the user ID
     */
    public int getUserId() {
        return userId;
    }

    /**
     * Sets the user ID.
     *
     * @param userId the user ID
     */
    public void setUserId(int userId) {
        this.userId = userId;
    }

    /**
     * Gets the user's name.
     *
     * @return the name
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the user's name.
     *
     * @param name the name
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Gets the user's email.
     *
     * @return the email
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the user's email.
     *
     * @param email the email
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * Gets the user's phone number.
     *
     * @return the phone number
     */
    public String getPhone() {
        return phone;
    }

    /**
     * Sets the user's phone number.
     *
     * @param phone the phone number
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * Gets the user's password.
     *
     * @return the password
     */
    public String getPassword() {
        return password;
    }

    /**
     * Sets the user's password.
     *
     * @param password the password
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * Gets the user's role ID.
     *
     * @return the role ID
     */
    public int getRoleId() {
        return roleId;
    }

    /**
     * Sets the user's role ID.
     *
     * @param roleId the role ID
     */
    public void setRoleId(int roleId) {
        this.roleId = roleId;
    }

    /**
     * Checks if the user account is active.
     *
     * @return true if active, false otherwise
     */
    public boolean isActive() {
        return isActive;
    }

    /**
     * Sets the active status of the user.
     *
     * @param active the active status
     */
    public void setActive(boolean active) {
        this.isActive = active;
    }

    /**
     * Checks if is approved.
     *
     * @return true, if is approved
     */
    public boolean isApproved() {
        return isApproved;
    }

    /**
     * Sets the approved.
     *
     * @param approved the new approved status
     */
    public void setApproved(boolean approved) {
        isApproved = approved;
    }

}
